import { File, Paths } from 'expo-file-system';

const LATENCY_FILE_NAME = 'llm-inference-latency.json';
const LATENCY_SCHEMA_VERSION = 1;

export interface LlmInferenceLatencySample {
  recordedAt: string;
  utterance: string;
  inferenceMs: number;
  /** Time from generate() start until the first visible token callback. */
  ttftMs?: number | null;
  /** Prompt tokens consumed by the most recent generation. */
  promptTokenCount?: number | null;
  /** Tokens generated by the most recent generation. */
  generatedTokenCount?: number | null;
  /** Prompt and generated tokens combined. */
  totalTokenCount?: number | null;
}

interface LatencyFile {
  version: number;
  samples: LlmInferenceLatencySample[];
}

export function buildLlmInferenceSample(input: {
  utterance: string;
  startedAt: number;
  finishedAt: number;
  firstTokenAt?: number | null;
  promptTokenCount?: number | null;
  generatedTokenCount?: number | null;
  totalTokenCount?: number | null;
}): LlmInferenceLatencySample | null {
  const inferenceMs = Math.round(input.finishedAt - input.startedAt);
  if (!Number.isFinite(inferenceMs) || inferenceMs < 0) {
    return null;
  }
  const firstTokenAt = input.firstTokenAt;
  const ttftMs =
    typeof firstTokenAt === 'number' &&
    Number.isFinite(firstTokenAt) &&
    firstTokenAt >= input.startedAt &&
    firstTokenAt <= input.finishedAt
      ? Math.round(firstTokenAt - input.startedAt)
      : null;
  const tokenCount = (value: number | null | undefined) =>
    typeof value === 'number' &&
    Number.isInteger(value) &&
    value >= 0
      ? value
      : null;

  return {
    recordedAt: new Date(input.finishedAt).toISOString(),
    utterance: input.utterance,
    inferenceMs,
    ttftMs,
    promptTokenCount: tokenCount(input.promptTokenCount),
    generatedTokenCount: tokenCount(input.generatedTokenCount),
    totalTokenCount: tokenCount(input.totalTokenCount),
  };
}

export function isCurrentLatencyLog(parsed: unknown): parsed is LatencyFile {
  if (!parsed || typeof parsed !== 'object') {
    return false;
  }
  const file = parsed as LatencyFile;
  return file.version === LATENCY_SCHEMA_VERSION && Array.isArray(file.samples);
}

function latencyFile(): File {
  return new File(Paths.document, LATENCY_FILE_NAME);
}

function writeSamples(samples: LlmInferenceLatencySample[]): void {
  const file = latencyFile();
  if (!file.exists) {
    file.create();
  }
  file.write(
    JSON.stringify({ version: LATENCY_SCHEMA_VERSION, samples }, null, 2),
  );
}

async function readSamples(): Promise<LlmInferenceLatencySample[]> {
  const file = latencyFile();
  if (!file.exists) {
    return [];
  }
  const raw = await file.text();
  if (!raw.trim()) {
    return [];
  }
  const parsed: unknown = JSON.parse(raw);
  if (!isCurrentLatencyLog(parsed)) {
    writeSamples([]);
    return [];
  }
  return parsed.samples.filter(
    (sample) =>
      sample &&
      typeof sample === 'object' &&
      typeof sample.inferenceMs === 'number' &&
      Number.isFinite(sample.inferenceMs),
  );
}

let persistQueue: Promise<void> = Promise.resolve();

export function recordLlmInferenceLatency(
  sample: LlmInferenceLatencySample,
): void {
  persistQueue = persistQueue
    .then(async () => {
      const samples = await readSamples();
      samples.push(sample);
      writeSamples(samples);
      console.log(
        `[latency] wrote ${samples.length} sample(s) to ${latencyFile().uri}`,
      );
    })
    .catch((error) => {
      console.warn('[latency] failed to persist sample', error);
    });
}
